version: "3"
services:
  postgres:
    image: postgres:13.2
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: devpassword
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  mongo:
    image: mongo:3
    expose:
      - "27017"
    volumes:
      - ./mongo/data:/data/db
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api/:/app
    ports:
      - "3000:3000"
  react:
    build:
      context: ./react
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./react:/app
    ports:
      - "8080:8080"
